name: Generate Snake

permissions:
  contents: write  # Grant write access to contents

on:
  schedule:
    # Every 12 hours
    - cron: "0 */12 * * *"

  # This command allows us to run the Action manually from the Actions tab.
  workflow_dispatch:

  # Also run on every push to the main branch
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Generate the snake files in './dist/' for dark mode
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: iftekharrifat09  # Your GitHub username
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark  # Dark mode palette
            dist/github-contribution-grid-snake.gif?color_snake=red&color_dots=#161B22,#8dbdff,#64a1f4,#4b91f1,#3c7dd9  # Red snake for dark mode

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Show build status
        run: git status

      - name: Push new files to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          commit_message: Update snake animations for dark mode
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
