name: Generate Snake

# Controls when the action will run.
on:
  schedule:
    # Every 12 hours
    - cron: "0 */12 * * *"

  # This command allows us to run the Action manually from the Actions tab.
  workflow_dispatch:
  
  # Also run on every push to the main branch
  push:
    branches:
      - main

# The sequence of runs in this workflow:
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3
    
      - name: Generate the snake files
        uses: Platane/snk@v3
        with:
          github_user_name: iftekharrifat09  # Updated username
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Debugging step: Check if the 'dist' directory exists and list its contents
      - name: Check if 'dist' directory exists
        run: |
          if [ -d dist ]; then
            echo "'dist' directory exists"
            ls dist
          else
            echo "'dist' directory does not exist!"
          fi

      # Push the snake files to the output branch
      - name: Push snake files to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          commit_message: Update snake animations
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
