name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Generate the snake files
        uses: Platane/snk@v3
        with:
          github_user_name: iftekharrifat09  # Your GitHub username
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Check if 'dist' directory exists and list contents
        run: |
          if [ -d dist ]; then
            echo "'dist' directory exists:"
            ls -al dist
          else
            echo "'dist' directory does not exist!"
            exit 1
          fi

      - name: Push snake files to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: ./dist  # Ensure the correct path to 'dist'
          commit_message: Update snake animations
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
