name: Generate Snake

permissions:
  contents: write  # Grant write access to contents

on:
  schedule:
    # Every 12 hours
    - cron: "0 */12 * * *"

  # This command allows us to run the Action manually from the Actions tab.
  workflow_dispatch:

  # Also run on every push to the main branch
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Generate the snake SVG file in './dist/'
        uses: Platane/snk/svg-only@v3  # Use the svg-only version
        id: snake-svg
        with:
          github_user_name: iftekharrifat09  # Your GitHub username
          outputs: |
            dist/snake.svg?palette=github-dark&color_snake=red  # Set snake color to red

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Show build status
        run: git status

      - name: Push new SVG file to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          commit_message: Update snake SVG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
